apiVersion: v1
appVersion: "25.11"
description: ClickHouse is an open source column-oriented database management
  system capable of real time generation of analytical data reports using SQL
  queries
home: https://clickhouse.yandex/
icon: https://clickhouse.yandex/images/logo.png
keywords:
  - clickhouse
  - olap
  - database
name: clickhouse
sources:
  - https://github.com/thiagoloureiro/clickhouse.chart
version: '25.11'
maintainers:
  - name: thiagoloureiro
